### ISSUE TITLE
Rollup Major Update

### ISSUE THREAD

**Issue by shellscape** [drg-adaptive/serverless-rollup-plugin#15]
👋  hey there thanks very much for putting this plugin together. I'm about to give it a shot for some of my work projects. I'm also a member of the Rollup core team and (kind of sort of) lead on the official plugins repo for Rollup.

I was wondering if you had plans to update the Rollup version to 2.x and the plugins along with it.

**Comment by theBenForce** [comment]
Hi shellscape, glad to hear you may get some use out of this plugin!

I'll take a look at upgrading rollup to 2.x. Were there any major changes to the API?
